services:
  app:
    build: .
    image: little-chef
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=/data/dev.db
    volumes:
      - type: bind
        source: ./data
        target: /data