import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { validateRequest } from "@/lib/auth/lucia";
import { CTALink } from "./components/CallToAction/Link";
import { Header } from "./components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  const { user } = await validateRequest();

  return (
    <html lang="en" className="min-h-[100dvh] bg-white">
      <body className={`${inter.className} min-h-[100dvh]`}>
        <div
          className="h-[100svh]"
          // className="magic-grid h-[100svh]"
          // style={{
          //   gridTemplateRows:
          //     "[header-start] min-content [header-end content-start] 1fr [content-end action-start] min-content [action-end]",
          // }}
        >
          {props.children}
        </div>
      </body>
    </html>
  );
}
