import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Little Chef",
    template: "%s | Little Chef",
  },
  description: "Generated by create next app",
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en" className="min-h-dvh">
      <body className={`${inter.className} dark:bg-stone-900 dark:text-white`}>
        <div>
          <div className="mx-auto min-h-dvh">
            <div className="min-h-svh">
              <Suspense>{props.children}</Suspense>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
